### ISSUE TITLE
Include ffmpeg exe files in package

### ISSUE THREAD

**Issue by Julusian** [mcmtroffaes/ffmpeg-nuget#2]
It would be useful to have the ffmpeg.exe/ffprobe.exe files included in the nuget package. It won't affect the size much and would be very useful to us for https://github.com/CasparCG/server where we are currently downloading them manually to be included in our builds.

**Comment by mcmtroffaes** [comment]
My apologies for not responding to this earlier. The sole goal of this nuget package is to distribute the headers, import libraries, and runtime dlls in a way that makes it easy to compile projects with msvc against the official ffmpeg libraries - no more, no less. If you do need the full executables, I kindly suggest using the ones that are distributed at https://ffmpeg.zeranoe.com/builds/ (these will have exactly the same feature set as the libraries of this nuget package).

**Comment by Julusian** [comment]
No problem, this has been a very low priority nice to have, that slightly simplifies some parts of our build.

To clarify our situation a little, the main application (c++) uses the dlls. And we have a helper program (written in node) which uses the ffmpeg exe directly. This means we are having to use both nuget and a zeranoe download.
As we want to use the exact same version, this makes it a bit fiddlier to update as there are a couple of places where we have to update the versions to keep it all in sync.
