### ISSUE TITLE
The term 'Start-FileDownload' is not recognized

### ISSUE THREAD

**Issue by Sodininkas** [mcmtroffaes/ffmpeg-nuget#3]
Hello,
error:
Start-FileDownload : The term 'Start-FileDownload' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At D:\OBJECTDETECT\ffmpeg-nuget-master\install.ps1:7 char:34
+ if (!(Test-Path "$dev32.zip")) { Start-FileDownload "http://ffmpeg.ze ...
+                                  ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Start-FileDownload:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by mcmtroffaes** [comment]
Yeah, it's a powershell command that is available on appveyor:

https://www.appveyor.com/docs/how-to/download-file/

I wasn't aware anyone would try to run this locally, but for that purpose maybe another command could be used. Unfortunately, I'm not a powershell wizard ^^ so what would you suggest?

**Comment by mcmtroffaes** [comment]
The install script is now using Net.WebClient to download the files, so it should be easier to run the script locally now. Thanks again for reporting!
