### ISSUE TITLE
Error while installing ffmpeg.nightly form Nuget

### ISSUE THREAD

**Issue by MFarrukh54** [mcmtroffaes/ffmpeg-nuget#4]
Hi,
I am getting an error while installing ffmpeg.Nightly. This is the error message.

>Could not install package 'FFmpeg.Nightly 20190404.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
I also searched for it's solution but found nothing. Kindly tell me the possible issue and what's the solution for it.

Moreover tell me that this package can contains all functionality of ffmpeg or not?

Thanks.

**Comment by mcmtroffaes** [comment]
This package only targets native. I suggest that you have a look at the examples to see how to set it up properly in MSVC:

https://github.com/mcmtroffaes/ffmpeg-nuget/tree/master/test

As for functionality, everything from the official builds is included. The official homepage links to a readme where you can see all configuration options: https://ffmpeg.zeranoe.com/builds/

Does this help?

**Comment by MFarrukh54** [comment]
Thanks for your reply.
You told me about how to integrate it in MSVC. Can you please tell me how to use it in c# wpf. If any example available please share it.

Thanks again.

**Comment by mcmtroffaes** [comment]
This nuget package only targets native. It does not target C#. For that, you'll need to look for another package that provides a suitable wrapper. Sorry I can't be more helpful!
